### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by thanhhff** [vutung3196/DevC-Challenge-Data-Science#1]
Nhận xét: 
- Phần SQL: bạn làm tốt, lần sau cố gắng nhé !
- Phần Python:
+ Task 3 yêu cầu của mình là từ 1 nhé chứ không phải từ 0.
+ Task 5 mình có thể lấy A[-2] thay vì việc phải sử dụng A[n-2] vì trong Python hỗ trợ index âm để truy ngược từ dưới lên.

**Comment by vutung3196** [comment]
Thank you so much :d
